name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main  # Trigger only on main branch pushes

permissions:
  packages: write  # Enable pushing to GHCR
  contents: read   # Allow reading repo contents

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-arch Docker image
        env:
          IMAGE_NAME: "ghcr.io/itssiem/shot-scan"
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:latest \
            --push .
